name: Deploy onboarding ms

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - "apps/onboarding-ms/**"
      - "infra/container_apps/onboarding-ms/**"
      - "apps/pom.xml"
      - "pom.xml"
  
  workflow_dispatch:

jobs:

  release_dev:
    uses: ./.github/workflows/call_release_ms.yml
    name: '[Dev] OnBoarding ms Release'
    if: github.ref_name == 'main'
    secrets: inherit
    with:
      environment: dev

  release_uat:
    uses: ./.github/workflows/call_release_ms.yml
    name: '[UAT] OnBoarding ms Release'
    if: startsWith(github.ref_name, 'releases/')
    secrets: inherit
    with:
      environment: uat

  release_prod:
    uses: ./.github/workflows/call_release_ms.yml
    name: '[Prod] OnBoarding ms Release'
    if: startsWith(github.ref_name, 'releases/')
    secrets: inherit
    with:
      environment: prod
