name: Deploy PNPG Container Apps infra

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - './infra/container_apps/onboarding-ms/env/dev-pnpg'
      - './infra/container_apps/onboarding-ms/env/uat-pnpg'
      - './infra/container_apps/onboarding-ms/env/prod-pnpg'
      - '!./infra/container_apps/onboarding-ms/env/**'
      - './infra/container_apps/onboarding-ms/**'

  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev
        - uat
        - prod

jobs:

  release_dev:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[Dev] Container Apps Infra Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
    secrets: inherit
    with:
      environment: dev
      tf_environment: dev-pnpg
      dir: ./infra/container_apps/onboarding-ms
      env_vars: |
        TF_VAR_image_tag=sha-$(git rev-parse --short ${{ github.sha }})

  release_uat:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[UAT] Container Apps Infra Release'
    if: startsWith(github.ref_name, 'releases/')
    secrets: inherit
    with:
      environment: uat
      tf_environment: uat-pnpg
      dir: ./infra/container_apps/onboarding-ms
      env_vars: |
        TF_VAR_image_tag=sha-$(git rev-parse --short ${{ github.sha }})

  release_prod:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[Prod] Container Apps Infra Release'
    if: ${{ inputs.env == 'prod' }}
    secrets: inherit
    with:
      environment: prod
      tf_environment: prod-pnpg
      dir: ./infra/container_apps/onboarding-ms
      env_vars: |
        TF_VAR_image_tag=sha-$(git rev-parse --short ${{ github.sha }})