name: Deploy PNPG onboarding functions

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - 'apps/onboarding-functions/**'
      - "apps/pom.xml"
      - "pom.xml"

  workflow_dispatch:

jobs:

  release_dev:
    uses: ./.github/workflows/call_release_function.yml
    name: '[Dev] OnBoarding function Release'
    if: github.ref_name == 'main'
    secrets: inherit
    with:
      environment: dev
      short_env: d-pnpg

  release_uat:
    uses: ./.github/workflows/call_release_function.yml
    name: '[UAT] OnBoarding function Release'
    if: startsWith(github.ref_name, 'releases/')
    secrets: inherit
    with:
      environment: uat
      short_env: u-pnpg

  release_prod:
    uses: ./.github/workflows/call_release_function.yml
    name: '[Prod] OnBoarding function Release'
    if: startsWith(github.ref_name, 'releases/') 
    secrets: inherit
    with:
      environment: prod
      short_env: p-pnpg
